// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsMicroService.DataAccessLayer.DBContext;

#nullable disable

namespace ProductsMicroService.DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260411184650_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProductsMicroService.DataAccessLayer.Entity.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("double");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = new Guid("1a9df78b-3f46-4c3d-9f2a-1b9f69292a77"),
                            Category = "Electronics",
                            ProductName = "Apple iPhone 15 Pro Max",
                            QuantityInStock = 50,
                            UnitPrice = 1299.99
                        },
                        new
                        {
                            ProductID = new Guid("2c8e8e7c-97a3-4b11-9a1b-4dbe681cfe17"),
                            Category = "Electronics",
                            ProductName = "Samsung Foldable Smart Phone 2",
                            QuantityInStock = 100,
                            UnitPrice = 1499.99
                        },
                        new
                        {
                            ProductID = new Guid("3f3e8b3a-4a50-4cd0-8d8e-1e178ae2cfc1"),
                            Category = "Furniture",
                            ProductName = "Ergonomic Office Chair",
                            QuantityInStock = 25,
                            UnitPrice = 249.99000000000001
                        },
                        new
                        {
                            ProductID = new Guid("4c9b6f71-6c5d-485f-8db2-58011a236b63"),
                            Category = "Furniture",
                            ProductName = "Coffee Table with Storage",
                            QuantityInStock = 30,
                            UnitPrice = 179.99000000000001
                        },
                        new
                        {
                            ProductID = new Guid("5d7e36bf-65c3-4a71-bf97-740d561d8b65"),
                            Category = "Electronics",
                            ProductName = "Samsung QLED 75 inch",
                            QuantityInStock = 20,
                            UnitPrice = 1999.99
                        },
                        new
                        {
                            ProductID = new Guid("6a14f510-72c1-42c8-9a5a-8ef8f3f45a0d"),
                            Category = "Furniture",
                            ProductName = "Running Shoes",
                            QuantityInStock = 75,
                            UnitPrice = 49.990000000000002
                        },
                        new
                        {
                            ProductID = new Guid("7b39ef14-932b-4c84-9187-55b748d2b28f"),
                            Category = "Accessories",
                            ProductName = "Anti-Theft Laptop Backpack",
                            QuantityInStock = 60,
                            UnitPrice = 59.990000000000002
                        },
                        new
                        {
                            ProductID = new Guid("8c5f6e73-68fc-49d9-99b4-aecc3706a4f4"),
                            Category = "Electronics",
                            ProductName = "LG OLED 65 inch",
                            QuantityInStock = 15,
                            UnitPrice = 1499.99
                        },
                        new
                        {
                            ProductID = new Guid("9e7e7085-6f4e-4921-8f15-c59f084080f9"),
                            Category = "Furniture",
                            ProductName = "Modern Dining Table",
                            QuantityInStock = 10,
                            UnitPrice = 699.99000000000001
                        },
                        new
                        {
                            ProductID = new Guid("10d7b110-ecdb-4921-85a4-58a5d1b32bf4"),
                            Category = "Electronics",
                            ProductName = "PlayStation 5",
                            QuantityInStock = 40,
                            UnitPrice = 499.99000000000001
                        },
                        new
                        {
                            ProductID = new Guid("11f2e86a-9d5d-42f9-b3c2-3e4d652e3df8"),
                            Category = "Furniture",
                            ProductName = "Executive Office Desk",
                            QuantityInStock = 18,
                            UnitPrice = 299.99000000000001
                        },
                        new
                        {
                            ProductID = new Guid("12b369b7-9101-41b1-a653-6c6c9a4fe1e4"),
                            Category = "HomeAppliances",
                            ProductName = "Breville Smart Blender",
                            QuantityInStock = 50,
                            UnitPrice = 129.99000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
